apiVersion : apps/v1
kind: Deployment
metadata:
  name: metasploitable 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metasploitable
  template:
    metadata:
      labels:
        app: metasploitable 
    spec:
      containers:
        - name: metasploitable 
          image: waftraining.azurecr.io/metasploitable
          ports:
          - containerPort: 80